# Generated by Django 5.2.17 on 2026-10-07 08:06

import accounts.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginCodeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('invite_token', models.CharField(default=accounts.models.new_token, max_length=32, unique=True)),
                ('last_visit_at', models.DateTimeField(blank=True, null=True)),
                ('news_since', models.DateTimeField(blank=True, null=True)),
                ('watch_region', models.CharField(blank=True, help_text="Empty: the app's default.", max_length=2, verbose_name='country')),
                ('services', models.JSONField(blank=True, default=list, verbose_name='my streaming services')),
                ('own_services', models.JSONField(blank=True, default=list, verbose_name='my other services')),
                ('ai_approved', models.BooleanField(default=False, verbose_name='AI approved')),
                ('ai_daily_limit', models.DecimalField(blank=True, decimal_places=2, help_text="Empty: the app's default. 0: no AI.", max_digits=6, null=True, verbose_name='AI limit per day (USD)')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['email'],
            },
        ),
    ]
