# Generated by Django 5.2.17 on 2026-10-07 07:54

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('import', 'Import')], max_length=10)),
                ('model', models.CharField(blank=True, max_length=50)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=4, default=0, max_digits=8, verbose_name='cost (USD)')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI usage',
                'verbose_name_plural': 'AI usage',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('movie', 'Movie'), ('show', 'TV show')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1870), django.core.validators.MaxValueValidator(2100)])),
                ('season', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(500)])),
                ('season_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('episodes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('want', 'Want to watch'), ('watching', 'Watching'), ('watched', 'Watched')], default='want', max_length=10)),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text='1 to 5 stars', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('notes', models.TextField(blank=True)),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('watched_at', models.DateTimeField(blank=True, null=True)),
                ('tmdb_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='TMDB id')),
                ('poster_path', models.CharField(blank=True, max_length=100)),
                ('overview', models.TextField(blank=True)),
                ('genres', models.JSONField(blank=True, default=list)),
                ('providers', models.JSONField(blank=True, default=list, verbose_name='where to watch (TMDB)')),
                ('providers_checked_at', models.DateTimeField(blank=True, null=True)),
                ('own_providers', models.JSONField(blank=True, default=list, verbose_name='where to watch (added)')),
                ('providers_sync', models.BooleanField(default=True, verbose_name='keep where to watch updated from TMDB')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'entries',
                'ordering': ['-added_at'],
            },
        ),
        migrations.CreateModel(
            name='Import',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('add', 'Import'), ('link', 'Update')], default='add', max_length=10)),
                ('text', models.TextField()),
                ('add_as', models.CharField(choices=[('want', 'Want to watch'), ('watching', 'Watching'), ('watched', 'Watched')], default='want', max_length=10)),
                ('status', models.CharField(choices=[('running', 'Reading'), ('done', 'Done'), ('failed', 'Failed')], default='running', max_length=10)),
                ('used_ai', models.BooleanField(default=False)),
                ('found', models.PositiveIntegerField(default=0)),
                ('message', models.TextField(blank=True, help_text='Why it failed, or a note about how it was read.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PendingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(max_length=300, verbose_name='imported text')),
                ('kind', models.CharField(choices=[('movie', 'Movie'), ('show', 'TV show')], default='movie', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('season', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('want', 'Want to watch'), ('watching', 'Watching'), ('watched', 'Watched')], default='want', max_length=10)),
                ('tmdb_id', models.PositiveIntegerField(blank=True, null=True)),
                ('poster_path', models.CharField(blank=True, max_length=100)),
                ('candidates', models.JSONField(blank=True, default=list)),
                ('sure', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='lists.entry')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='lists.import')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sure', 'created_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('emoji', models.CharField(blank=True, max_length=8)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='import',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='lists.tag'),
        ),
        migrations.AddField(
            model_name='entry',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='entries', to='lists.tag'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_tag_name'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['user', 'kind', 'status'], name='lists_entry_user_id_54505e_idx'),
        ),
    ]
