# Generated by Django 5.2.17 on 2026-10-06 19:00

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('movie', 'Movie'), ('show', 'TV show')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1870), django.core.validators.MaxValueValidator(2100)])),
                ('status', models.CharField(choices=[('want', 'Want to watch'), ('watching', 'Watching'), ('watched', 'Watched')], default='want', max_length=10)),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text='1 to 5 stars', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('notes', models.TextField(blank=True)),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('watched_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'entries',
                'ordering': ['-added_at'],
                'indexes': [models.Index(fields=['user', 'kind', 'status'], name='lists_entry_user_id_54505e_idx')],
            },
        ),
    ]
