# Generated by Django 5.2.17 on 2026-10-07 12:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiusage',
            name='kind',
            field=models.CharField(choices=[('import', 'Import'), ('recommend', 'Recommendations')], max_length=10),
        ),
        migrations.CreateModel(
            name='RecommendationSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Choosing'), ('done', 'Done'), ('failed', 'Failed')], default='running', max_length=10)),
                ('fingerprint', models.CharField(blank=True, max_length=64)),
                ('requested', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_sets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('movie', 'Movie'), ('show', 'TV show')], max_length=10)),
                ('tmdb_id', models.PositiveIntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('poster_path', models.CharField(blank=True, max_length=100)),
                ('overview', models.TextField(blank=True)),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('providers', models.JSONField(blank=True, default=list)),
                ('state', models.CharField(choices=[('open', 'Open'), ('added', 'Added'), ('dismissed', 'Not for me')], default='open', max_length=10)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='lists.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='lists.recommendationset')),
            ],
            options={
                'ordering': ['position', 'pk'],
            },
        ),
    ]
